### ISSUE TITLE
No Connection To Kernel - Windows 7, Python 2.7, 64 bit

### ISSUE THREAD

**Issue by Iki-San** [lenguyenthedat/minimal-datascience#3]
I'm using Firefox 64 bit, have Miniconda 64 bit (Python 2.7.9).  
Every time I try and open a notebook, I get a broken link to my Python 2 kernel (initially it looks like it's connected, then it's not connected, and this switching happens a couple of times, and then it's just not connected).
After a while, in the command window I get some thing like:
     WebSocket ping timeout after 90003 ms.

Any suggestions? Thanks!

**Comment by lenguyenthedat** [comment]
Sounds like an unrelated problem (with Notebook) - I would suggest you take a look at http://jupyter.readthedocs.org/en/latest/install.html
